# Generated by Django 3.2.10 on 2022-01-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='お問い合わせした人のIPアドレス'),
            preserve_default=False,
        ),
    ]
