# Generated by Django 3.2.10 on 2022-01-28 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文日時')),
                ('paid', models.BooleanField(default=False, verbose_name='支払い確認済み')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pattern', verbose_name='商品に貼り付ける模様')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='カートに入れた人')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文日時')),
                ('delivered', models.BooleanField(default=False, verbose_name='配送済み')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pattern', verbose_name='商品に貼り付ける模様')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='カートに入れた人')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='カートに追加された日時')),
                ('ordered', models.BooleanField(default=False, verbose_name='注文済み')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pattern', verbose_name='商品に貼り付ける模様')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='カートに入れた人')),
            ],
        ),
    ]
